/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PisyaAbi } from "./PisyaAbi";

export { PisyaAbi__factory } from "./factories/PisyaAbi__factory";
