/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
} from "fuels";

interface PisyaAbiInterface extends Interface {
  functions: {
    initialize_bank: FunctionFragment;
    increment_bank: FunctionFragment;
    decrement_bank: FunctionFragment;
    get_bank: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize_bank",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "increment_bank",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "decrement_bank",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "get_bank",
    values?: undefined
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "initialize_bank",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "increment_bank",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "decrement_bank",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_bank",
    data: BytesLike
  ): DecodedValue;
}

export class PisyaAbi extends Contract {
  interface: PisyaAbiInterface;
  functions: {
    initialize_bank: InvokeFunction<[value: BigNumberish], bigint>;

    increment_bank: InvokeFunction<[], bigint>;

    decrement_bank: InvokeFunction<[], bigint>;

    get_bank: InvokeFunction<[], bigint>;
  };
}
